services:
    eliza:
        platform: linux/amd64
        command: ["pnpm", "start"]
        image: pitboss-agent
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        env_file:
            - .env
        ports:
            - "3000:3000"
        restart: always
